/* Generated By:JavaCC: Do not edit this line. MooplParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MooplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROC = 8;
  /** RegularExpression Id. */
  int FUN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int ARRAYOF = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int OUTPUT = 20;
  /** RegularExpression Id. */
  int LENGTH = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int SELF = 24;
  /** RegularExpression Id. */
  int NEW = 25;
  /** RegularExpression Id. */
  int OBJECT = 26;
  /** RegularExpression Id. */
  int ISNULL = 27;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 28;
  /** RegularExpression Id. */
  int ID = 29;
  /** RegularExpression Id. */
  int OP = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"proc\"",
    "\"fun\"",
    "\"class\"",
    "\"return\"",
    "\"arrayof\"",
    "\"boolean\"",
    "\"int\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"output\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"self\"",
    "\"new\"",
    "\"object\"",
    "\"isnull\"",
    "<INTEGER_LITERAL>",
    "<ID>",
    "<OP>",
  };

}
